name: Fail deployment

on:
  workflow_call:
    inputs:
      slack-channel:
        type: string
        default: testing
      slack-thread:
        type: string
        required: true

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
    - uses: archive/github-actions-slack@master
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        slack-channel: ${{ inputs.slack-channel }}
        slack-text: Deployment failed!
        slack-optional-thread_ts: ${{ inputs.slack-thread }}
        slack-optional-reply_broadcast: true
