name: Deploy to staging

on:
  workflow_call:
    inputs:
      ecr_registry:
        type: string
        required: true
      rancher_label:
        type: string
        required: true
      site_account:
        type: string
        required: true
      site_dir:
        type: string
        required: true
      site_stack:
        type: string
        required: true
      site_version:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes
        run: |
          npx @parameter1/rancher2cli dl \
            --wait --namespace staging-websites-${{ inputs.site_stack }} \
            basecms-website ${{ inputs.rancher_label }} \
            ${{ inputs.ecr_registry }}/base-cms-websites:${{ inputs.site_account }}-${{ inputs.site_dir }}-${{ inputs.site_version }}
        env:
          RANCHER_CLUSTERID: ${{ secrets.RANCHER_CLUSTERID_BASECMS }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
